1.0
RuslanMurin/SkillBox-Course2 pull request #1
Opened 2021-02-02 15:49 UTC by RuslanMurin

2021-02-03 08:26 UTC, ios-review requested changes
Клевая реализация второй компьютерной игры👍
Функция bound 🤩

Некоторые задания можно упростить, для некоторых есть дополнительные вопросы.

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> + //Класс описывает свойства и методы, протокол же их только обозначает. Соответсвенно класс - самостоятельный тип, который можно присвоить объекту, протокол же - нет.
Что значит описывает, а что обозначает?

Протокол тоже может быть самостоятельным типом.

```
protocol A {}
class AImpl: A {}

let a: A = AImpl()
```

Константа a является типом протокола A.

Раскроете подробнее?

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> + d) кортежи (Tuples).
Что из этого может реализовать протокол?

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +}
Для клетки шахматного поля можно создать отдельную модель.
Координаты клетки описываются цифрой 1-8 и буквой A-F.

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +    var delegate: ChessBoardDelegate { get }  //делегат
readonly?

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +protocol ChessEngine{
Попробуете реализовать оба протокола?

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +        return CGPoint(x: self.midX, y: self.midY)
self можно не указывать

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +    }
Реализуете еще через вычисляемое свойство?

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +        })
Чуть короче запись.
```
UIView.animate(withDuration: 2.0) {
    self.alpha = 0
}
```

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +        }
🔥

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +three.bound(minX: 1, maxX: 5)
Что должно вернуться?
`5.bound(min: 100, max: 1)`

Почему?

2021-02-03 08:26 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +}
👍

2021-02-04 16:13 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +}
Достаточно ли лаконично получилось?

2021-02-04 16:13 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +    var delegate: ChessBoardDelegate { get }  //делегат
Упустил set

2021-02-04 16:15 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +        return CGPoint(x: self.midX, y: self.midY)
А вообще в практической среде это было бы дурным тоном?

2021-02-04 16:18 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +    }
Добавил

2021-02-04 16:19 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +        })
👍🏻

2021-02-04 16:38 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +three.bound(minX: 1, maxX: 5)
Вернется 100, потому что под кейс попадает(я делал под "идеального" пользователя🙂). Обезопасил guard'ом, чтобы при несоответствии возвращался nil

2021-02-06 13:32 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +protocol ChessEngine{
Реализовал, объекты между собой общаются, реальные шахматы делать не стал - очень долго бы пришлось)

2021-02-06 13:46 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> + //Класс описывает свойства и методы, протокол же их только обозначает. Соответсвенно класс - самостоятельный тип, который можно присвоить объекту, протокол же - нет.
Описал в коде

2021-02-06 13:46 UTC, RuslanMurin commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> + d) кортежи (Tuples).
Все, кроме кортежей

2021-02-07 04:01 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +        return CGPoint(x: self.midX, y: self.midY)
Дурной тон - это нарушать договоренности в команде.

Правила code style - это договор внутри команды.
Как договоритесь, так и будет.

Согласно Swift API design guidelines https://swift.org/documentation/api-design-guidelines/ self используют только, когда это необходимо.
В данном случае self можно опустить.

В разных командах могут быть разные требования и видения, включая этот пункт.

2021-02-07 04:08 UTC, ios-review approved these changes
fine 🔥))

merge

2021-02-07 04:08 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> + будут принимать в себя классы AImpl и BImpl. Они будут вынуждены описывать одинаковые методы из протокола А, но вот делать они это могут совершенно по-разному. Соответственно объекты подписанные под
🔥

Дефолтная реализация все еще требуется создания конкретного типа, для которого можно создать объект, будь то класс/структура/перечисление.

2021-02-07 04:08 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +typealias ChessCoordinates = (alpha: CellAlphabetic, number: CellNumberic)
В typealias нельзя добавить функций, новых свойств, какой-то логики в целом.

Рекомендую для моделирования использовать структуры/перечисления или классы.

2021-02-07 04:08 UTC, ios-review commented on 1.0-Protocols-and-Extensions/1.0-Protocols-and-Extensions.playground/Contents.swift
> +        guard minX < maxX else { return nil }
Интересное решение👍

Мне кажется, что возвращение опционала может ввести в заблуждение клиента метода.
При каких условиях будет nil?

Условие min > max является критической ошибкой, так как нарушается логика и определение этих слов.
Это сравнимо с выходом за пределы массива, с переполнением типа.
Вероятно, крашить приложение будет более ожидаемым поведение для клиента.
При этом возвращать неопциональное значение.
Так как для существующих n, min и max значение bound всегда существует.
Эта функция непрерывная.

Для предусловий можно использовать https://developer.apple.com/documentation/swift/1540960-precondition

2021-02-08 14:43 UTC, merged