1.1
RuslanMurin/SkillBox-Course2 pull request #2
Opened 2021-02-08 17:45 UTC by RuslanMurin

Доброго времени суток, надеюсь, все понятно объяснил)

2021-02-09 15:30 UTC, ios-review requested changes
Очень мощные ответы и примеры🔥🔥🔥

Добавил еще несколько вопросов)

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +protocol ClassOnly: AnyObject{}
А так можно?
`protocol ClassOnly: class {}`
В чем разница?

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +}
🔥

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Официально, конечно, нельзя, extension лишь расширяют функционал, поэтому можно добавить лишь новые вычисляемые свойства. Можно лишь расширить инициализатор:
два способа обойти ограничение:
- https://stackoverflow.com/questions/25426780/how-to-have-stored-properties-in-swift-the-same-way-i-had-on-objective-c
- https://valv0.medium.com/computed-properties-and-extensions-a-pure-swift-approach-64733768112c

Приведете примеры обоих?

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Можно, не вложенные типы нет огрчничений
а протоколы можно?

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Можно, но соответственно надо реализовать обязательные методы/свойства
И как быть в таком случае со свойствами?

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Можно, но соответственно надо реализовать обязательные методы/свойства
Для случая если сами класс/структура/перечисление не доступны.

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Соответственно, если оно будет объявлено как let, то все будет правильно
Пример кода.

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +protocol ForEquatable: Equatable{}
`protocol OnlyForViewController: UIViewController {}`

Попробуйте реализовать этот протокол для любого другого класса.

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +protocol ForEquatable: Equatable{}
Можно ли так сделать для структур, перечислений?

2021-02-09 15:30 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +    func nonOptionalFunc() {}
```
protocol A {}
protocol B {}
typealias AB = A & B
```

2021-02-10 15:52 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +protocol ClassOnly: AnyObject{}
Ответил в коде

2021-02-10 15:53 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +}
🙂

2021-02-10 15:55 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Можно, не вложенные типы нет огрчничений
Нет, протокол не может помещаться внутри другой декларации, они объявляются только на глобальном уровне.

2021-02-11 15:02 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Соответственно, если оно будет объявлено как let, то все будет правильно
Добавил

2021-02-11 15:11 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +protocol ForEquatable: Equatable{}
Если рассматривать какой-то свой пользовательский класс:
`class TestClass: OnlyForViewController {}`
то это реализовать будет невозможно, а вот если его сначала наследовать от UIViewController, а затем уже подписывать под наш протокол, то такое будет допустимо
`class TestClass: UIViewController, OnlyForViewController {}`
Для структур и перечислений так не сделать, они не поддерживают наследование

2021-02-11 15:11 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +protocol ForEquatable: Equatable{}
Ну, и соответственно потому что наш протокол теперь class-only

2021-02-11 15:15 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +    func nonOptionalFunc() {}
Ага, то есть typealias на протоколы тоже распространяется, буду знать

2021-02-11 16:27 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Официально, конечно, нельзя, extension лишь расширяют функционал, поэтому можно добавить лишь новые вычисляемые свойства. Можно лишь расширить инициализатор:
Я попробовал оба, но второй мне кажется более лаконичным и чистым. + он чисто свифтовый

2021-02-11 16:28 UTC, RuslanMurin commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +//Можно, но соответственно надо реализовать обязательные методы/свойства
Получается, что нужно как раз обходить ограничения со stored property, как в примерах, что вы приводили

2021-02-11 22:43 UTC, ios-review approved these changes
all good

ca be merged

2021-02-11 22:43 UTC, ios-review commented on 1.1-Protocols-Additional/1.1-Protocols-Additional.playground/Contents.swift
> +}
🔥

Данные способы не рекомендуется использовать.
Но если уж очень хочется, то можно)

2021-02-11 22:45 UTC, merged