2.0
RuslanMurin/SkillBox-Course2 pull request #3
Opened 2021-02-08 17:51 UTC by RuslanMurin

Давно ждал дженерики, начнаю редактировать дипломный проект(его ведь можно использовать в портфолио?)

2021-02-09 17:38 UTC, ios-review requested changes
Клевые ответы на теорию.
Красивое АПИ либы анимаций.
Большинство заданий решено коротко, просто и эффективно.

Несколько можно доработать.

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +//} немного не понял, каким должно быть тело функции
Сигнатура функции верная.
Реализацию немного дополнить и все.

Есть несколько синтаксических способов реализовать возвращаемую функцию.
Указывая параметры и не указывая.

```
return {
    first($0)
    second($0)
}

return { parameter in
    first(parameter)
    second(parameter)
}
```

Обратите внимание, что возвращаемая функция принимает тип T в качестве входного параметра.
А значит в реализации замыкания (функции) необходимо указать этот параметр или воспользоваться анонимным именем ($0).

Этот же тип принимают в качестве параметра функции first и second.

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    var maxEl: Element? { return self.max() }
🔥

Реализуете собственный алгоритм?

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +        var temp = Array()
`var temp: [Element] = []`

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +            if temp.contains(el) == false{
`if !temp.contains(el)`

Немного проще, чем равенство false.

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +array.removeDuplicates()
Если элементы могут соответствовать протоколу Hashable, какую еще реализацию можно предложить?

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    return number * number * number
Оператор возведения в степень.

2 ^^ 5 = 32
5 ^^ 2 = 25
5 ^^ 3 = 125
etc.

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +func ~>(lh: Int, rh: inout Int){
code-style: пробел между ) и {
поправить везде по коду

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +var a = Int()
`var a = /*use literal value instead of init for Int type, e. g.*/ 100`

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +func <*<T: UITableViewDelegate>(delegate: T, tableView: UITableView){
Зачем дженерик?

Может просто delegate: UITableViewDelegate?

Кажется, что здесь использовать дженерик будет переобобщением.

2021-02-09 17:38 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +myView.backgroundColor
👍

2021-02-10 05:51 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +//} немного не понял, каким должно быть тело функции
Вот за объяснение с анонимным именем - огромная благодарность, я не очень смог понять его, когда изучал. И еще вопрос: получается, я могу при использовании, скажем, 3-х дженериков ссылаться как $0, $1, $3 и т.д.?

2021-02-10 06:30 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    var maxEl: Element? { return self.max() }
Почему нет)

2021-02-10 07:43 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +        var temp = Array()
исправил

2021-02-10 07:44 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +            if temp.contains(el) == false{
Согласен)

2021-02-10 07:48 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    return number * number * number
Реализовал

2021-02-10 07:50 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +func ~>(lh: Int, rh: inout Int){
Исправил

2021-02-10 07:53 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +var a = Int()
Сделано

2021-02-10 07:54 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +func <*<T: UITableViewDelegate>(delegate: T, tableView: UITableView){
Буду внимательнее

2021-02-10 07:55 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +myView.backgroundColor
☺️

2021-02-10 08:05 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +array.removeDuplicates()
Правильно ли я понял ваш вопрос?

2021-02-11 22:49 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +//} немного не понял, каким должно быть тело функции
Дженерик - это неопределенный тип данных на момент определения функции.
Дженерик становится конкретным типом, когда вызывается функция.

Анонимное имя используется для параметров замыкания, которые могут быть вполне известными типами, без дженериков.
Например,
```
let closureA: (Int) -> Void = {
    print($0)
}
let closureB: (Int, String) -> Void = {
    print($0, $1)
}
```

У closureA и closureB заранее известны (на момент определения) типы параметров, то есть они не дженерики, но при этом для самих параметров внутри реализации этих замыканий используются анонимные имена.
Правило для использования анонимных имен такое: необходимо обязательно использовать их все (если один, то $0, если два, то $0 и $1 и тд) либо использовать именованные параметры.

```
let closureC: (String, String, String) = { namedParameterA, namedParameterB, namedParameterC in
    // здесь реализация
}
```

https://docs.swift.org/swift-book/LanguageGuide/Closures.html раздел Shorthand Argument Names.

2021-02-11 22:53 UTC, ios-review requested changes
С функцией max перемудрили)
Алгоритм вычисления уникальных значений можно немного упростить.

2021-02-11 22:53 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    var maxEl: Element? { return self.sorted(by: >).first }
Воу)

Сложность алгоритма сортировки O(n * log n).
Сложность функции max() O(n).

Реализовать требовалось алгоритм с такой же сложностью, как и встроенная функция max().
Какой алгоритм будет со сложностью O(n) без использования встроенной функции?

2021-02-11 22:53 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +        self = buffer
Так можно?
`self = Array(Set(self))`

2021-02-16 15:58 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    var maxEl: Element? { return self.sorted(by: >).first }
ПРавильно понял?

2021-02-17 07:00 UTC, ios-review requested changes
Код с критической багой.
Правим.

2021-02-17 07:00 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    }
Небезопасно.
```
let ints: [Int] = []
print(ints.maxEl)
```

2021-02-17 07:00 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    }
и code-style: отступы поехали и пробелы не все

2021-02-17 07:00 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +}//Очень лаконично
Верно отметили, что порядок не сохраняется.
Какие есть способы сохранить порядок и оставить такую же лаконичную запись?
Может есть упорядоченное множество?
Поищите?

2021-02-17 16:56 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +    }
обезопасил и исправил

2021-02-17 17:58 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +}//Очень лаконично
Не получается, я уже давно искал, нашел 2 пути, но кажется, что это все не то:
1. NSOrderedSet - его я не могу использовать, так как компилятор вырвет ошибку
2. Создать пользовательскую структуру упорядоченного сета, но это совсем не лаконично
Что я упускаю? Кучу источников перелопатил, и все впустую

2021-02-18 05:47 UTC, ios-review requested changes
Круто, что нашли NSOrderedSet🔥

Предлагаю доделать эту реализацию.

2021-02-18 05:47 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +        guard !self.isEmpty else { return nil }
self можно опускать, в случаях когда нет необходимости писать явно self:
`guard !isEmpty else { return nil }`

2021-02-18 05:47 UTC, ios-review commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +        self = Array(_immutableCocoaArray: NSOrderedSet(array: self))
NSOrderedSet не является swift коллекцией в полном смысле.
Поэтому NSOrderedSet не является и дженерик структурой данных.

Для преобразования объекта NSOrderedSet в массив необходимо воспользоваться соответствующим свойством.
https://developer.apple.com/documentation/foundation/nsorderedset/1411531-array
А затем привести это свойство к типу массива [Element].
```
extension Array where Element: Hashable {
    mutating func removeDuplicates1() {
        self = NSOrderedSet(array: self).array as! [Element]
    }
}
```

Почему здесь безопасно использовать принудительное приведение к типу `as! [Element]`?

2021-03-01 21:01 UTC, RuslanMurin commented on 2.0-Generics/2.0-Generics.playground/Contents.swift
> +        self = Array(_immutableCocoaArray: NSOrderedSet(array: self))
[Element] приводим к [Element] судя по всему поэтому Force unwrap и уместен

2021-03-01 21:03 UTC, merged